name: pl@ntbert
channels:
  - defaults
dependencies:
  - pip
  - pip:
      - accelerate==0.25.0
      - datasets==2.16.1
      - evaluate==0.4.1
      - numpy==1.26.3
      - openpyxl==3.1.2
      - pandas==2.1.4
      - requests==2.31.0
      - scikit-learn==1.3.2
      - setuptools==57.4.0
      - torch==2.1.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - verde==1.8.0